--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/pjz9n-pm-pl/Mission
build-by-default: true
branches:
  - v2
projects:
  Mission:
    icon: icon.png
    libs:
      - src: dktapps-pm-pl/pmforms/pmforms
        version: 1.0.0
...
